#!/bin/bash
ls -na root/alx-system_engineering-devops/0x00-shell_basics/11-lists/0-current_working_directory/10-back/11-lists/2-bring_me_home/3-listfiles/4-listmorefiles/5-listfilesdigitonly/6-firstdirectory/7-movethatfile/8-firstdelete/9-firstdirdeletion/README.md
